version: "3.7"
services:

  mysql:
    image: mariadb:10.3
    container_name: mysql-container
    ports:
       - 3306:3306
    volumes:
       - container-volume:/var/lib/mysql
       - ./mysql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
       MYSQL_ROOT_PASSWORD: soccer481200


  dsi324:
    build: ./web/.
    links:
      - mysql
    ports:
      - 5000:5000
      - 80:80
    volumes:
      - ./web/.:/code
    environment:
      FLASK_ENV: development

volumes:
  container-volume:
